AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MetadataTable
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: ResourceType
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: S
        - AttributeName: ResourceName
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
        - AttributeName: ResourceType
          KeyType: RANGE  # Sort Key
      GlobalSecondaryIndexes:
        - IndexName: TimestampIndex
          KeySchema:
            - AttributeName: Timestamp
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: ResourceNameIndex
          KeySchema:
            - AttributeName: ResourceName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  LambdaMetadataTableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt LambdaMetadataTable.Arn