AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MetadataTable
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: CreatedAt
          AttributeType: N
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CreatedAtIndex
          KeySchema:
            - AttributeName: CreatedAt
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  LambdaMetadataTableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt LambdaMetadataTable.Arn